apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-pipeline-samples
  annotations:
    backstage.io/techdocs-ref: dir:.
#     harness.io/project-url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/home/orgs/default/projects/vigneshproject/details
#     circleci.com/project-slug: github/vigneswara-propelo/python-pipeline-samples
    gitlab.com/project-id: '43877214'
    jenkins.io/github-folder: 'CDS-68313' 
spec:
  type: service
  lifecycle: experimental
  owner: team-a
