apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-pipeline-samples
  annotations:
    harness.io/project-url: https://app.harness.io/ng/#/account/0QvSt4c0TSiO-jLqZD3Mcg/ci/orgs/default/projects/pythondemo
spec:
  type: service
  lifecycle: experimental
  owner: team-a
