apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-pipeline-samples
  annotations:
    backstage.io/techdocs-ref: dir:docs
    harness.io/project-url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/home/orgs/default/projects/vigneshproject/details
spec:
  type: service
  lifecycle: experimental
  owner: team-a
